Titanic - Machine Learning from Disaster

Este es un ejemplo de clasificación, o sobrevive un pasajero:1 o no sobrevive:0

Por otro lado, fijaos en el dataset. Hay columnas que seguramente podamos prescindir de ellas. ¿Es importante o relevante el número de ticket de un pasajero para decidir si sobrevive o no?

1 - Escoged bien las features.

Por otro lado hay algunos tricks que podéis aplicar. Fijaos en el nombre... Aparentemente no nos dice nada o no debería ser relevante para saber si un pasajero sobrevive o no, pero.... en algunos hay cierta marca de estatus social que puede decantar la balanza.

Por otro lado, hay 2 variables que habla de la familia que tiene a bordo ese pasajero, una hace referencia a los hermanos y cónyuges y otra a los padres e hijos... quizás juntándolas tenga más sentido.

Para enviar los resultados a kaggle deberás de concatenar en un dataframe el PassengerId de test y las prediciones.

submission = pd.DataFrame({
"PassengerId": test["PassengerId"],
"Survived": preds
})

Después expórtalo a csv y súbelo.

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
df = pd.read_csv('./data/gender_submission.csv')
df = pd.read_csv('./data/test.csv')
df = pd.read_csv('./data/train.csv')

In [24]:
print(f'Filas : {df.shape[0]}')
print(f'Columnas : {df.shape[1]}')
df.head()

Filas : 891
Columnas : 12

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

El número de ticket no está relacionado con la supervivencia del pasajero

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
dtypes: int64(2)
memory usage: 6.7 KB

In [19]:
df.describe()

       PassengerId    Survived
count   418.000000  418.000000
mean   1100.500000    0.363636
std     120.810458    0.481622
min     892.000000    0.000000
25%     996.250000    0.000000
50%    1100.500000    0.000000
75%    1204.750000    1.000000
max    1309.000000    1.000000